[package]
name = "day03"
version = "0.1.0"
authors = ["Nicolas Bigaouette <nbigaouette@gmail.com>"]

[dependencies]
log = "0.4"
ndarray = "0.12"

[dev-dependencies]
criterion = "0.2"
env_logger = "0.6"

[[bench]]
name = "aoc_benchmark"
harness = false
