[package]
name = "day02"
version = "0.1.0"
authors = ["Nicolas Bigaouette <nbigaouette@gmail.com>"]

[dependencies]
# log = "0.4"
itertools = "0.7"
strsim = "0.8.0"

[dev-dependencies]
criterion = "0.2"
env_logger = "0.6"

[[bench]]
name = "aoc_benchmark"
harness = false
