(function() {var implementors = {};
implementors["day06"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"day06/initial/enum.Cell.html\" title=\"enum day06::initial::Cell\">Cell</a>",synthetic:false,types:["day06::initial::Cell"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"day06/struct.Position.html\" title=\"struct day06::Position\">Position</a>",synthetic:false,types:["day06::Position"]},];
implementors["day09"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"day09/initial/struct.Idx.html\" title=\"struct day09::initial::Idx\">Idx</a>",synthetic:false,types:["day09::initial::Idx"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"day09/initial/struct.PlayerIdx.html\" title=\"struct day09::initial::PlayerIdx\">PlayerIdx</a>",synthetic:false,types:["day09::initial::PlayerIdx"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"day09/initial/struct.DoubleLinkedListIterator.html\" title=\"struct day09::initial::DoubleLinkedListIterator\">DoubleLinkedListIterator</a>&lt;'a&gt;",synthetic:false,types:["day09::initial::DoubleLinkedListIterator"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"day09/initial/struct.DoubleLinkedListRevIterator.html\" title=\"struct day09::initial::DoubleLinkedListRevIterator\">DoubleLinkedListRevIterator</a>&lt;'a&gt;",synthetic:false,types:["day09::initial::DoubleLinkedListRevIterator"]},];
implementors["day12"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"day12/enum.PotState.html\" title=\"enum day12::PotState\">PotState</a>",synthetic:false,types:["day12::PotState"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
