[package]
name = "day04"
version = "0.1.0"
authors = ["Nicolas Bigaouette <nbigaouette@gmail.com>"]

[dependencies]
# log = "0.4"
lazy_static = "1.2"
regex = "1.1"

[dev-dependencies]
criterion = "0.2"
env_logger = "0.6"

[[bench]]
name = "aoc_benchmark"
harness = false
